layout_spectrum: 1
typography_spectrum: 0.6855549
color:
  saturation: 0.7244898
  brandStrength: 0.2639778
  lightness: 0.3539205
  rhythmicContrast: 0.6707841
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Jcnorman
